SERVICE_NAMES_ADDR = "IP_PUBLICO_DO_NAMING_SERVICE"
SERVICE_NAMES_TCP_PORT = 5000

SERVER_NAME = "comparisonServer"
SERVER_TYPE = "server"
PEER_TYPE = "peer"

SERVER_PORT = 5678
PEER_TCP_PORT = 5679
PEER_UDP_PORT = 5679

DB_FILE_PREFIX = "replica_db_peer_"
